/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gyte.ai.eardic.chessknight.gui;

import aima.core.search.framework.SearchAgent;
import gyte.ai.eardic.chessknight.ai.CKPAStarSearch;
import gyte.ai.eardic.chessknight.ai.SearchResult;
import gyte.ai.eardic.chessknight.board.ChessBoard;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Emre
 */
public class MainUI extends JFrame
{

    private static final long serialVersionUID = 1L;

    private ChessBoard chessBoard = null;

    private Thread probSolver;

    /**
     * Creates new form MainUI
     */
    public MainUI()
    {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        heuristicGroup = new javax.swing.ButtonGroup();
        controlPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        buildBoardButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        columnField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        rowField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        barrierPercent = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        h1CheckBox = new javax.swing.JRadioButton();
        h2CheckBox = new javax.swing.JRadioButton();
        h3CheckBox = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        h1Ne = new javax.swing.JLabel();
        h2Ne = new javax.swing.JLabel();
        h3Ne = new javax.swing.JLabel();
        h1Bf = new javax.swing.JLabel();
        h2Bf = new javax.swing.JLabel();
        h3Bf = new javax.swing.JLabel();
        h1Pc = new javax.swing.JLabel();
        h2Pc = new javax.swing.JLabel();
        h3Pc = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        statusBar = new javax.swing.JLabel();
        terminateButton = new javax.swing.JButton();
        scrollPanel = new javax.swing.JScrollPane();
        boardPanel = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chess Knight Problem Solver");
        setMinimumSize(new java.awt.Dimension(740, 480));
        addComponentListener(new java.awt.event.ComponentAdapter()
        {
            public void componentResized(java.awt.event.ComponentEvent evt)
            {
                formComponentResized(evt);
            }
        });

        controlPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chess Board"));
        jPanel1.setToolTipText("Enter Row and Column size of checc board");

        buildBoardButton.setText("Build Chess Board");
        buildBoardButton.setToolTipText("Creates a board with row x column");
        buildBoardButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buildBoardButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Column");

        jLabel1.setText("Row");

        jLabel6.setText("Barrier %");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buildBoardButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(columnField)
                            .addComponent(rowField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(barrierPercent)))
                .addGap(3, 3, 3))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rowField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(columnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(barrierPercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buildBoardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Heuristics"));
        jPanel2.setToolTipText("Select one of three heuristics to solve CNP");

        heuristicGroup.add(h1CheckBox);
        h1CheckBox.setText("King Heuristic");
        h1CheckBox.setToolTipText("Based on movement of the king in chess");

        heuristicGroup.add(h2CheckBox);
        h2CheckBox.setText("Castle-2 Heuristic");
        h2CheckBox.setToolTipText("Based on castle in chess but using max 2 square");

        heuristicGroup.add(h3CheckBox);
        h3CheckBox.setText("Pawn Heuristic");
        h3CheckBox.setToolTipText("Based on the pawn in chess but can move one square to every direction");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(h1CheckBox)
                    .addComponent(h2CheckBox)
                    .addComponent(h3CheckBox))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(h1CheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(h2CheckBox)
                .addGap(3, 3, 3)
                .addComponent(h3CheckBox))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("P.Cost & N.Expa & B.Factor"));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("KH :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("CH :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("PH :");

        h1Ne.setText("0");

        h2Ne.setText("0");

        h3Ne.setText("0");

        h1Bf.setText("0,000");

        h2Bf.setText("0,000");

        h3Bf.setText("0,000");

        h1Pc.setText("0");

        h2Pc.setText("0");

        h3Pc.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addComponent(h3Pc))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(h2Pc))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(h1Pc)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(h1Ne, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(h2Ne, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(h3Ne, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(h1Bf))
                            .addComponent(h3Bf, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(h2Bf)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(h1Ne)
                    .addComponent(h1Bf)
                    .addComponent(h1Pc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(h2Ne)
                    .addComponent(h2Bf)
                    .addComponent(h2Pc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(h3Ne)
                    .addComponent(h3Bf)
                    .addComponent(h3Pc)))
        );

        startButton.setBackground(new java.awt.Color(41, 198, 60));
        startButton.setText("Start Solving");
        startButton.setToolTipText("Solves Chess Knight Problem using selected heuristics respectively.");
        startButton.setEnabled(false);
        startButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                startButtonActionPerformed(evt);
            }
        });

        progressBar.setStringPainted(true);

        statusBar.setText("Status :");

        terminateButton.setBackground(new java.awt.Color(255, 51, 51));
        terminateButton.setText("Terminate");
        terminateButton.setEnabled(false);
        terminateButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                terminateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(startButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addComponent(statusBar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(terminateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusBar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(terminateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        boardPanel.addMouseWheelListener(new java.awt.event.MouseWheelListener()
        {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt)
            {
                boardPanelMouseWheelMoved(evt);
            }
        });

        javax.swing.GroupLayout boardPanelLayout = new javax.swing.GroupLayout(boardPanel);
        boardPanel.setLayout(boardPanelLayout);
        boardPanelLayout.setHorizontalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 588, Short.MAX_VALUE)
        );
        boardPanelLayout.setVerticalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 481, Short.MAX_VALUE)
        );

        scrollPanel.setViewportView(boardPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scrollPanel)
                    .addComponent(controlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buildBoardButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buildBoardButtonActionPerformed
    {//GEN-HEADEREND:event_buildBoardButtonActionPerformed

        new Thread(new Runnable()
        {
            public void run()
            {
                try
                {
                    progressBar.setValue(0);
                    // Solve - Build button's disabled.
                    enableButtons(false, false, false);

                    int inputRow, inputCol;
                    int barrierRate;
                    // Get input values from form
                    barrierRate = Integer.parseInt(barrierPercent.getText());
                    inputRow = Integer.parseInt(rowField.getText());
                    inputCol = Integer.parseInt(columnField.getText());
                    // Check inputs
                    if (inputRow <= 0 || inputCol <= 0)
                    {
                        throw new NumberFormatException();
                    }
                    if (barrierRate < 0 || barrierRate > 100)
                    {
                        throw new NumberFormatException();
                    }

                    progressBar.setValue(10);
                    statusBar.setText("Status : Creating Board.");

                    // Create board, random barrier
                    chessBoard = new ChessBoard(inputRow, inputCol, boardPanel.getSize(), barrierRate);

                    progressBar.setValue(50);
                    statusBar.setText("Status : Preparing Board.");

                    // Add the board to gui
                    boardPanel.setPreferredSize(chessBoard.getSize());
                    boardPanel.removeAll();
                    boardPanel.add(chessBoard);

                    // Solve - Build button's enabled.
                    enableButtons(true, true, false);

                    progressBar.setValue(100);
                    statusBar.setText("Status : Board's Done.");

                }
                catch (NumberFormatException ex)
                {
                    enableButtons(true, true, false);
                    progressBar.setValue(0);
                    statusBar.setText("Status : Check board inputs !");
                    errorDialog("Row and Column cannot be negative and Barrier percent "
                            + "should be between 0 and 100.", "Input Error");
                    ex.printStackTrace();
                }
            }
        }).start();

    }//GEN-LAST:event_buildBoardButtonActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_formComponentResized
    {//GEN-HEADEREND:event_formComponentResized
        if (chessBoard != null)
        {
            chessBoard.setSize(boardPanel.getSize());
        }
    }//GEN-LAST:event_formComponentResized

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_startButtonActionPerformed
    {//GEN-HEADEREND:event_startButtonActionPerformed

        probSolver = new Thread(new Runnable()
        {

            @Override
            public void run()
            {
                try
                {
                    progressBar.setValue(0);
                    // Solve - Build button's disabled.
                    enableButtons(false, false, true);

                    if (h1CheckBox.isSelected())
                    {
                        statusBar.setText("Status : King H's Running...");
                        chessBoard.resetBoard();
                        showSolution(h1Pc, h1Ne, h1Bf, CKPAStarSearch.solveByKingMethod(chessBoard));
                    }
                    if (h2CheckBox.isSelected())
                    {
                        statusBar.setText("Status : Castle H's Running...");
                        chessBoard.resetBoard();
                        showSolution(h2Pc, h2Ne, h2Bf, CKPAStarSearch.solveByCastleMethod(chessBoard));
                    }
                    if (h3CheckBox.isSelected())
                    {
                        statusBar.setText("Status : Pawn H's Running...");
                        chessBoard.resetBoard();
                        showSolution(h3Pc, h3Ne, h3Bf, CKPAStarSearch.solveByPawnMethod(chessBoard));
                    }
                    statusBar.setText("Status : All Heuristics're Done!...");
                    progressBar.setValue(100);

                    // Solve - Build button's enabled.
                    enableButtons(true, true, false);

                }
                catch (OutOfMemoryError e)
                {
                    enableButtons(true, true, false);
                    progressBar.setValue(0);
                    statusBar.setText("Status : Not enough memory !");
                    errorDialog("Insufficient Memory !", "OutOfMemory");
                    e.printStackTrace();
                }
                catch (Exception e)
                {
                    enableButtons(true, true, false);
                    progressBar.setValue(0);
                    statusBar.setText("Status : Search canceled !");
                    e.printStackTrace();
                }
            }
        });
        //START the solver thread
        probSolver.start();
    }//GEN-LAST:event_startButtonActionPerformed

    private void terminateButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_terminateButtonActionPerformed
    {//GEN-HEADEREND:event_terminateButtonActionPerformed
        // TODO add your handling code here:
        try
        {
            if (probSolver != null)
            {
                probSolver.interrupt();
                probSolver.stop();
                chessBoard.resetBoard();
                enableButtons(true, true, false);
                statusBar.setText("Status : Termination's success !");
            }
        }
        catch (Exception e)
        {
            statusBar.setText("Status : Failed to terminate !");
            chessBoard.resetBoard();
            enableButtons(true, true, false);
        }
    }//GEN-LAST:event_terminateButtonActionPerformed

    private void boardPanelMouseWheelMoved(java.awt.event.MouseWheelEvent evt)//GEN-FIRST:event_boardPanelMouseWheelMoved
    {//GEN-HEADEREND:event_boardPanelMouseWheelMoved
        // TODO add your handling code here:
        if (evt.getWheelRotation() > 0)
        {
            chessBoard.zoomIn();
        }
        else
        {
            chessBoard.zoomOut();
        }
        boardPanel.setSize(chessBoard.getSize());
        boardPanel.setPreferredSize(chessBoard.getSize());
        boardPanel.revalidate();
        boardPanel.repaint();
    }//GEN-LAST:event_boardPanelMouseWheelMoved

    private void showSolution(JLabel pc, JLabel ne, JLabel bf, SearchAgent ag)
    {
        SearchResult res;
        res = CKPAStarSearch.getResults(ag);

        //Show analysis results
        pc.setText(res.getPathCost() + "");
        bf.setText(String.format("%.4f", res.getBrachingFactor()));
        ne.setText(res.getExpandedNode() + "");

        //Show solution path
        chessBoard.showSolution(ag.getActions());
    }

    private void errorDialog(String message, String head)
    {
        JOptionPane.showMessageDialog(this,
                message,
                head,
                JOptionPane.ERROR_MESSAGE);
    }

    private void enableButtons(final boolean solve, final boolean build, final boolean ter)
    {
        startButton.setEnabled(solve);
        buildBoardButton.setEnabled(build);
        terminateButton.setEnabled(ter);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        //Solves IllegalArgumentException:Comparison method violates its general contract!
        System.setProperty("java.util.Arrays.useLegacyMergeSort", "true");

        try
        {
            /* Set the Metal look and feel */
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch (ClassNotFoundException ex)
        {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (UnsupportedLookAndFeelException ex)
        {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        }


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barrierPercent;
    private javax.swing.JLayeredPane boardPanel;
    private javax.swing.JButton buildBoardButton;
    private javax.swing.JTextField columnField;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel h1Bf;
    private javax.swing.JRadioButton h1CheckBox;
    private javax.swing.JLabel h1Ne;
    private javax.swing.JLabel h1Pc;
    private javax.swing.JLabel h2Bf;
    private javax.swing.JRadioButton h2CheckBox;
    private javax.swing.JLabel h2Ne;
    private javax.swing.JLabel h2Pc;
    private javax.swing.JLabel h3Bf;
    private javax.swing.JRadioButton h3CheckBox;
    private javax.swing.JLabel h3Ne;
    private javax.swing.JLabel h3Pc;
    private javax.swing.ButtonGroup heuristicGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JTextField rowField;
    private javax.swing.JScrollPane scrollPanel;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel statusBar;
    private javax.swing.JButton terminateButton;
    // End of variables declaration//GEN-END:variables
}
