/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gyte.ai.eardic.chessknight.gui;

import aima.core.agent.Action;
import aima.core.environment.eightpuzzle.EightPuzzleFunctionFactory;
import aima.core.environment.eightpuzzle.EightPuzzleGoalTest;
import aima.core.environment.eightpuzzle.MisplacedTilleHeuristicFunction;
import aima.core.search.framework.GraphSearch;
import aima.core.search.framework.Problem;
import aima.core.search.framework.Search;
import aima.core.search.framework.SearchAgent;
import aima.core.search.informed.AStarSearch;
import aima.gui.demo.search.EightPuzzleDemo;
import gyte.ai.eardic.chessknight.ai.CKPAStarSearch;
import gyte.ai.eardic.chessknight.ai.CKPCastleHeuristic;
import gyte.ai.eardic.chessknight.ai.CKPFunctionFactory;
import gyte.ai.eardic.chessknight.ai.CKPGoalTest;
import gyte.ai.eardic.chessknight.ai.CKPZeroHeuristic;
import gyte.ai.eardic.chessknight.ai.SearchResult;
import gyte.ai.eardic.chessknight.board.ChessBoard;
import java.util.Iterator;
import java.util.List;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Emre
 */
public class MainUI extends JFrame
{

    private static final long serialVersionUID = 1L;

    private ChessBoard chessBoard = null;

    /**
     * Creates new form MainUI
     */
    public MainUI()
    {
        initComponents();
        //EightPuzzleDemo.main(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        controlPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        buildBoardButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        columnField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        rowField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        barrierPercent = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        h1CheckBox = new javax.swing.JCheckBox();
        h2CheckBox = new javax.swing.JCheckBox();
        h3CheckBox = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        h1Ne = new javax.swing.JLabel();
        h2Ne = new javax.swing.JLabel();
        h3Ne = new javax.swing.JLabel();
        h1Bf = new javax.swing.JLabel();
        h2Bf = new javax.swing.JLabel();
        h3Bf = new javax.swing.JLabel();
        h1Pc = new javax.swing.JLabel();
        h2Pc = new javax.swing.JLabel();
        h3Pc = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        boardPanel = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chess Knight Problem Solver");
        setMinimumSize(new java.awt.Dimension(720, 450));
        addComponentListener(new java.awt.event.ComponentAdapter()
        {
            public void componentResized(java.awt.event.ComponentEvent evt)
            {
                formComponentResized(evt);
            }
        });

        controlPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chess Board"));
        jPanel1.setToolTipText("Enter Row and Column size of checc board");

        buildBoardButton.setText("Build Chess Board");
        buildBoardButton.setToolTipText("Creates a board with row x column");
        buildBoardButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buildBoardButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Column");

        jLabel1.setText("Row");

        jLabel6.setText("Barrier %");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(buildBoardButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(columnField)
                            .addComponent(rowField)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(barrierPercent)))
                .addGap(3, 3, 3))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rowField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(columnField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(barrierPercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buildBoardButton))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Heuristics"));
        jPanel2.setToolTipText("Select one of three heuristics to solve CNP");

        h1CheckBox.setText("Zero Heuristic");

        h2CheckBox.setText("Castle Heuristic");

        h3CheckBox.setText("Queen Heuristic");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(h1CheckBox)
                    .addComponent(h2CheckBox)
                    .addComponent(h3CheckBox))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(h1CheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(h2CheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(h3CheckBox))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("P.Cost & N.Expa & B.Fac"));

        jLabel3.setText("ZH");

        jLabel4.setText("CH");

        jLabel5.setText("QH");

        h1Ne.setText("0");

        h2Ne.setText("0");

        h3Ne.setText("0");

        h1Bf.setText("0");

        h2Bf.setText("0");

        h3Bf.setText("0");

        h1Pc.setText("0");

        h2Pc.setText("0");

        h3Pc.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(h3Pc))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(h2Pc))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(h1Pc)))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(h1Ne, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(h2Ne, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(h3Ne, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(h1Bf))
                            .addComponent(h3Bf, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(h2Bf)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(h1Ne)
                    .addComponent(h1Bf)
                    .addComponent(h1Pc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(h2Ne)
                    .addComponent(h2Bf)
                    .addComponent(h2Pc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(h3Ne)
                    .addComponent(h3Bf)
                    .addComponent(h3Pc)))
        );

        startButton.setText("Start Solving");
        startButton.setToolTipText("Solves Chess Knight Problem using selected heuristics respectively.");
        startButton.setEnabled(false);
        startButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                startButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlPanelLayout.createSequentialGroup()
                        .addComponent(startButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        boardPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        boardPanel.setToolTipText("Use Chess Board Panel to create the board.");

        javax.swing.GroupLayout boardPanelLayout = new javax.swing.GroupLayout(boardPanel);
        boardPanel.setLayout(boardPanelLayout);
        boardPanelLayout.setHorizontalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );
        boardPanelLayout.setVerticalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boardPanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(controlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boardPanel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buildBoardButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buildBoardButtonActionPerformed
    {//GEN-HEADEREND:event_buildBoardButtonActionPerformed
        try
        {
            int inputRow, inputCol;
            int barrierRate;
            // Get input values from form
            barrierRate = Integer.parseInt(barrierPercent.getText());
            inputRow = Integer.parseInt(rowField.getText());
            inputCol = Integer.parseInt(columnField.getText());
            // Check inputs
            if (inputRow <= 0 || inputCol <= 0)
            {
                throw new NumberFormatException();
            }
            if (barrierRate < 0 || barrierRate > 100)
            {
                throw new NumberFormatException();
            }

            System.out.println("ChessBoard inputs are valid.Creating board...");

            // Create board
            chessBoard = new ChessBoard(inputRow, inputCol, boardPanel.getSize());
            //Random barriers
            chessBoard.addBarrierRandomly(barrierRate);

            System.out.println("ChessBoard's been created and being added to gui...");

            // Add the board to gui
            boardPanel.removeAll();
            boardPanel.add(chessBoard);

            // Enable solve button
            startButton.setEnabled(true);

            System.out.println("ChessBoard's been added to gui.Done.");
        }
        catch (NumberFormatException ex)
        {
            JOptionPane.showMessageDialog(this,
                    "Row and Column cannot be negative and Barrier percent should be between 0 and 100.",
                    "Input Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buildBoardButtonActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_formComponentResized
    {//GEN-HEADEREND:event_formComponentResized
        if (boardPanel.getComponentCount() != 0)
        {
            boardPanel.getComponent(0).setSize(boardPanel.getSize());
        }
    }//GEN-LAST:event_formComponentResized

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_startButtonActionPerformed
    {//GEN-HEADEREND:event_startButtonActionPerformed
        // TODO add your handling code here:        
        if (h1CheckBox.isSelected())
        {
            SearchResult res;
            SearchAgent ag = CKPAStarSearch.solveByZeroMethod(chessBoard);
            res = CKPAStarSearch.getResults(ag);
            h1Pc.setText(res.getPathCost() + "");
            h1Bf.setText(res.getBrachingFactor() + "");
            h1Ne.setText(res.getExpandedNode() + "");
        }
        if (h2CheckBox.isSelected())
        {
            SearchResult res;
            SearchAgent ag = CKPAStarSearch.solveByCastleMethod(chessBoard);
            res = CKPAStarSearch.getResults(ag);
            h2Pc.setText(res.getPathCost() + "");
            h2Bf.setText(res.getBrachingFactor() + "");
            h2Ne.setText(res.getExpandedNode() + "");
        }
        if (h3CheckBox.isSelected())
        {
            SearchResult res;
            SearchAgent ag = CKPAStarSearch.solveByQueenMethod(chessBoard);
            res = CKPAStarSearch.getResults(ag);
            h3Pc.setText(res.getPathCost() + "");
            h3Bf.setText(res.getBrachingFactor() + "");
            h3Ne.setText(res.getExpandedNode() + "");
        }
    }//GEN-LAST:event_startButtonActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        try
        {
            /* Set the Metal look and feel */
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex)
        {
            Logger.getLogger(MainUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barrierPercent;
    private javax.swing.JLayeredPane boardPanel;
    private javax.swing.JButton buildBoardButton;
    private javax.swing.JTextField columnField;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JLabel h1Bf;
    private javax.swing.JCheckBox h1CheckBox;
    private javax.swing.JLabel h1Ne;
    private javax.swing.JLabel h1Pc;
    private javax.swing.JLabel h2Bf;
    private javax.swing.JCheckBox h2CheckBox;
    private javax.swing.JLabel h2Ne;
    private javax.swing.JLabel h2Pc;
    private javax.swing.JLabel h3Bf;
    private javax.swing.JCheckBox h3CheckBox;
    private javax.swing.JLabel h3Ne;
    private javax.swing.JLabel h3Pc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JTextField rowField;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
